### ISSUE TITLE
目前用到检测插件，没有hook到任何信息

### ISSUE THREAD

**Issue by lcj168** [whytry-GAR/UserPricacyApiCheck#1]

**Comment by whytry-GAR** [comment]
这是来自QQ邮箱的自动回复邮件。您发给我的信件已经收到。我会尽早查看，谢谢

**Comment by whytry-GAR** [comment]
根据你的描述，有两个可能哈
1，你的app没有调用到readme 中描述的方法，所以没有hook和打印日志
2，你手机没有正确安装xpoesd，并启用这个检测的插件（这个插件是要在xpoesd环境下hook的），需要你检查下
